{% set name = "tangram_dummyatoms" %}


package:
  name: {{ name|lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v')[1:] }}

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
  run:
    - python
    - pychimera     >=0.2.6
    - libtangram
    - ambermini

about:
  home: http://github.com/insilichem/tangram_dummyatoms
  license: MIT
  license_family: MIT

  summary: 'Easy to prepare MD inputs for metal systems'

  description: |
    Apply the Cationic Dummy Atom approach to parametrize
    metal-containing systems using the Ambertoools suite.
  doc_url: http://tangram-suite.readthedocs.io/en/latest/tangram_dummymetal.html
  dev_url: https://github.com/insilichem/tangram_dummyatoms


